### PR TITLE
Update AdGuard Home to v0.106.1

### PR DESCRIPTION
**Pull request by abdulisik**
Alternatively, we can change it to image: adguard/adguardhome:latest to always pull the latest: https://hub.docker.com/r/adguard/adguardhome/tags?page=1&ordering=last_updated

### CODE REVIEW

**Comment by eiddor** [comment]
Hey @abdulisik - Thanks for the PR!

For project stability reasons, we generally try to let a release "bake" for a week before updating the repo (with AdGuard there tends to be a couple of point releases after each major).  So we definitely want to pin to a specific version for each PR.

Could you update your PR to v0.106.1?  We'll probably pull it on on Thursday or so assuming there are no other releases.

Thanks!

**Comment by eiddor** [comment]
@abdulisik As I was saying :-) If you want to update the commit to v0.106.2, we'll pull it in next week.

**Comment by abdulisik** [comment]
I got the point, thank you. I'll keep updating the PR for the patched versions.

**Comment by eiddor** [comment]
@abdulisik Oh no worries, I was just laughing because yet another point release just came out a few minutes ago as we were discussing this :-)

**Comment by eiddor** [comment]
@abdulisik Sorry - one more tiny request, could you squash your commits here down to one?  I'll merge it once that's done:
```
# rebase while in your doc_update_unbound branch where the
# last 2 commits are the ones we want to work with, hence HEAD~2
git rebase -i HEAD~2

```
Change your second commit from pick to fixup or f, save and quit.

```
# force push to your branch, rewriting history as if only one commit ever existed
git push -f
```

**Comment by eiddor** [comment]
Replaced by #9

**Pull request closed without merging**
